[directory]
fish_style_pwd_dir_length = 2

[java]
disabled=true

[conda]
ignore_base=false

[character]
vicmd_symbol="[î˜« â¯](bold red)"

[status]
disabled=false

[env_var.PETSC_ARCH]
variable = 'PETSC_ARCH'
format = '([$symbol$env_value]($style)) '
symbol = 'ğŸ…Ÿ '
default = ''
style = 'bold cyan'
